Task_1_1_1
Nikolay56615/OOP pull request #1
Opened 2024-09-05 13:39 UTC by Nikolay56615

2024-09-09 08:01 UTC, galinabykova requested changes

2024-09-09 08:01 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/lebedev/HeapSort.java
> +    public int[] retArr() {
Мне не нравится этот метод. 

Во-первых, рассмотрим такой код
```java
HeapSort heapSort = new HeapSort();
var arr = heapSort.heapsort(new int[]{-6, 1, 4, 6, 8});
arr[0] = 0;
var sortArr = heapSort.retArr();
System.out.println(sortArr[0]);
```
Не думаю, что это интуитивно понятный интерфейс.

Во-вторых, согласно твоему апи возможно использовать один объект для сортировки нескольких массивов, что, по моему мнению, может плодить ошибки.

2024-09-09 08:01 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/lebedev/HeapSort.java
> +    private int[] arr;
поясни, пожалуйста, зачем ты сделал поля? Почему не передаёшь массив как один входную переменную метода?

2024-09-09 08:01 UTC, galinabykova commented on Task_1_1_1/Graphic.xlsx
а можно скриншот, пожалуйста?

2024-09-09 09:47 UTC, Nikolay56615 commented on Task_1_1_1/Graphic.xlsx
![image](https://github.com/user-attachments/assets/dc6ecddb-3117-4036-9620-8b0de9e80901)
Там время, которое считается в Java вроде в нано секундах, так что такие большие числа

2024-09-09 09:53 UTC, Nikolay56615 commented on Task_1_1_1/src/main/java/ru/nsu/lebedev/HeapSort.java
> +    public int[] retArr() {
Вообще, у меня каких-то ошибок быть не должно, так как в функции heapsort массив arr клонируется, а следовательно то, что вы arr[0] = 0; повлияло только на ваш внешний массив, а не тот, что в классе, следовательно System.out.println(arr[0]); и System.out.println(sortArr[0]); выведет разные ответы. Если использовать один объект, то внутри объекта arr постоянно будет меняться на новый, так что никаких конфликтов не должно быть. Мне кажется, что удобнее создать объект класса один раз, чем его пересоздавать.

2024-09-09 09:55 UTC, Nikolay56615 commented on Task_1_1_1/src/main/java/ru/nsu/lebedev/HeapSort.java
> +    private int[] arr;
Просто для удобства. Таким образом один объект можно использовать для сортировки разных массивов без пересоздания переменной класса HeapSort. Я привык это делать еще с программирования на python с его self. переменными класса

2024-09-10 04:19 UTC, galinabykova requested changes
остался только reviewdog

2024-09-10 07:06 UTC, galinabykova approved these changes

2024-09-10 07:19 UTC, galinabykova approved these changes

2024-09-10 07:21 UTC, merged