Task_1_2_2
Nikolay56615/OOP pull request #10
Opened 2024-10-27 07:38 UTC by Nikolay56615

2024-10-27 15:45 UTC, galinabykova requested changes
мягкий засчитан, но я пока сильно не смотрела код, потому что мне нужно изучить алгоритм, который ты используешь, так что ожидаю нового запроса на ревью в ближайшее время

2024-10-27 15:45 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/Dict.java
> +public class Dict<T, D> {
Мне по названию было непонятно, что это за класс. Предлагаю, например, HashTableEntry

2024-10-27 15:45 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
> +    public boolean equals(HashTable<K, V> other) {
мне кажется, лучше всё-таки переопределить equals из Object, если считаешь, что так лучше, обоснуй)

2024-10-27 15:45 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
тут у тебя не классическое решение этой задачи, можешь обосновать/кинуть ссылку на обоснование асимптотики структуры данных, которую ты используешь?

2024-10-27 15:45 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
> +    public boolean equals(HashTable<K, V> other) {
мне кажется, хэш-таблицы, у которых одинаковые элементы хранятся в разном порядке, должны быть равны

2024-10-27 16:02 UTC, Nikolay56615 commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
Я вообще код на хэш таблицу брал из курса по императивному программированию, когда мы ее реализовывали. Вот тут можно просмотреть https://neerc.ifmo.ru/wiki/index.php?title=%D0%A0%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BA%D0%BE%D0%BB%D0%BB%D0%B8%D0%B7%D0%B8%D0%B9 про Линейный поиск и Удаление элемента без пометок. Возможно, можно было бы использовать какие-то методы из java, но я решил просто свой прошлый код доработать, он вроде в асимптотику попадает

2024-10-27 16:10 UTC, Nikolay56615 commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
II) Открытая адресация (open addressing).

Если нужно добавить элемент в ячейку, а ячейка занята, то добавляем элемент в следующую ячейку.
Если и она занята, то выбираем следующую... и т.д. пока не найдём сводобную ячейку.

Пример:
     0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15 
   +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
   |   |   | A | P | Q | X |   |   |   | T | Y |   |   | W |   | Y |
   +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+

   chi(A) = 2  chi(P) = 2  chi(Q) = 3  chi(X) = 4
   chi(T) = 9  chi(Y) = 9
   chi(W) = 13  chi(Y) = 15

При выполнении любой операции сначала вычисляется хеш-функция j = chi(k).
Далее нужно просмотреть все занятые ячейки начиная с j-ой и заканчивая первой пустой ячейкой после неё.

Таким образом, вся таблица разбивается на "отрезки" (runs) подряд идущих занятых клеток.
Время работы каждой операции определяется длиной такого отрезка.
При n/m <= C < 1 длина отрезка в среднем константная (без доказательства).
Например, можно поддерживать n/m <= 2/3, тогда отрезки в среднем будут очень короткие.
В таком случае время выполнения любой операции равно O(1) в среднем.

Замечание: что делать, если в нарисованную выше таблицу надо добавить новый элемент с хешом 15 ?
Обычно массив хеш-таблицы зацикливают, и новый элемент попадёт в ячейку 0.
Благодаря зацикливанию, в таблицу всегда можно добавить элемент, если в ней есть хотя бы одна свободная ячейка (хотя если свободных ячеек мало, то это будет небыстро).

Как доказать, что хеш-таблица с открытой адресацией верно работает?
Дело в том, что всегда выполняется следующее условие ("инвариант"):
  Если в j-ой ячейке таблицы лежит элемент с ключом k и chi(k) = i, то все ячейки в отрезке от i-ой до j-ой должны быть заняты.
Легко убедиться, что этот инвариант сохраняется в процессе работы (от добавлений не может нарушиться).

Это в лекции по императивному было

2024-10-27 16:18 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
Поняла, спасибо)

2024-11-03 15:34 UTC, galinabykova requested changes

2024-11-03 15:34 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lebedev/hashtable/HashTable.java
> +    private K[] keys;
используй  ArrayList и постарайся избавиться от почти всех @SuppressWarnings("unchecked" (скорее всего, большая часть предупреждений нужны из-за того, что массивы не дружат с дженериками). Проставляй тип дженерика, везде, где возможно, если тип неизвестен используй <?>

2024-11-04 12:30 UTC, galinabykova approved these changes

2024-11-04 12:40 UTC, merged