Task_1_3_1
Nikolay56615/OOP pull request #11
Opened 2024-11-09 06:27 UTC by Nikolay56615

2024-11-12 04:07 UTC, galinabykova requested changes
мягкий засчитан (вчера, так как ты прислал решение в срок)

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +            throw new RuntimeException("Error closing file", e);
а почему тут ты решил использовать RuntimeException?

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +public abstract class AbstractStringFinder {
в этом файле ты используешь возвращаемые значения для ошибок. Это альтернативное исключениям решение, которое обычно не используют в  java. Расскажи, почему ты решил сделать так

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/StringFinder.java
> +    protected void findingSubstring() {
а почему ты решил именно так разделить классы? почему этот метод выделен в отдельную сущность? (просто вопрос, менять не надо)

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +            return -1;
это магическая константа

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/lebedev/stringfinder/StringFinderTest.java
> +        predictedList.add((long) 1048575);
можно сразу сделать строковый литерал типа long так: 1048575L

2024-11-12 04:07 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/lebedev/stringfinder/StringFinderTest.java
нужны ещё тесты с ресурсами)

2024-11-18 08:08 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +            throw new RuntimeException("Error closing file", e);
жду ответ)

2024-11-18 08:09 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +public abstract class AbstractStringFinder {
и тут)

2024-11-18 08:09 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/StringFinder.java
> +    protected void findingSubstring() {
и тут)

2024-11-18 08:18 UTC, galinabykova requested changes

2024-11-18 08:18 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +    static final int FALSEVALUE = -1;
тут наверно лучше добавить нижнее подчёркивание)
FALSE_VALUE

2024-11-18 08:18 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +    static final int FALSEVALUE = -1;
для читаемости

2024-11-18 08:47 UTC, Nikolay56615 commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +            throw new RuntimeException("Error closing file", e);
Вообще мне это среда разработки предложила:
![image](https://github.com/user-attachments/assets/0ddb0c77-4511-40fd-9366-ec5555b3d98a)
Но технически, RuntimeException - это непроверяемое исключение. То есть "исключение времени выполнения можно было бы избежать вызывающей стороной", что значит пользователь (как вызывающая сторона метода) должна убедиться, что эта ошибка вообще не произойдет (отсутствие файла) - как часть контракта.

2024-11-18 08:51 UTC, Nikolay56615 commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +public abstract class AbstractStringFinder {
Мне это тестить было удобно, так как программа не прерывалась, как было с отсутствием файлов в стандартном пути. То есть ошибки не фатальны для нее. Да и логировать это было проще, как мне кажется, я уже к try-catch привык)

2024-11-18 08:53 UTC, Nikolay56615 commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/StringFinder.java
> +    protected void findingSubstring() {
Как я понимаю, в абстрактных классах можно определять не критичные методы для реализации чего-то. А важные вещи - например, оптимальный алгоритм, нужно в отдельный класс выносить. Соображения секретности.)

2024-11-18 09:13 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +            throw new RuntimeException("Error closing file", e);
но тут проблема в том, что от IOException ты никак не защитишься - вдруг кто-то удалил файл, прежде чем ты начал его закрывать, поэтому тут, мне кажется, это не очень хорошее решение)

2024-11-18 09:16 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/lebedev/stringfinder/AbstractStringFinder.java
> +public abstract class AbstractStringFinder {
Принято) но вообще, мне кажется, лучше не смешивать разные способы без причин

2024-11-18 09:17 UTC, galinabykova requested changes
RuntimeException всё-таки нужно убрать

2024-11-18 09:54 UTC, galinabykova approved these changes

2024-11-18 13:13 UTC, merged