Task_1_4_1
Nikolay56615/OOP pull request #12
Opened 2024-11-24 13:57 UTC by Nikolay56615

2024-11-24 18:39 UTC, galinabykova requested changes

2024-11-24 18:39 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/CreditBook.java
> +    public Set<Grade> getGrades() {
мне кажется, этот метод можно сделать package-private. Он не то чтобы полезен пользователю, но при этом даёт ему менять оценочки, так как метод возвращает ссылку на поле

2024-11-24 18:39 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/AcademicDiscipline.java
> +    OBJECT_ORIENTED_PROGRAMMING("Object-Oriented Programming", DisciplineType.EXAM),
у вас ооп два семестра, в одном диф зачёт, во втором - экзамен. Это можно уложить в твою объектную модель?

2024-11-24 18:39 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/StudentCreditBook.java
> +    private Set<Grade> getLastAcademicGrades() {
перепиши тут через StreamAPI

2024-11-24 18:39 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/StudentCreditBook.java
> +    public boolean canObtainRedDiploma() {
и тут тоже)

2024-11-24 18:39 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/StudentCreditBook.java
> +    public boolean canObtainRedDiploma() {
перепиши без циклов, через StreamAPI

2024-11-25 02:26 UTC, Nikolay56615 commented on Task_1_4_1/src/main/java/ru/nsu/lebedev/examination/AcademicDiscipline.java
> +    OBJECT_ORIENTED_PROGRAMMING("Object-Oriented Programming", DisciplineType.EXAM),
Я не даю пользователю возможность устанавливать, что за тип предмета он сейчас имеет. Я могу доработать?

2024-11-25 06:33 UTC, galinabykova approved these changes

2024-11-25 08:53 UTC, merged