Task_1_1_2
Nikolay56615/OOP pull request #4
Opened 2024-09-14 04:27 UTC by Nikolay56615

2024-09-16 06:31 UTC, galinabykova requested changes
мягкий дедлайн засчитан

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +            if (result == 1) {
тут можно switch-case

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +                System.out.println("Вы выиграли раунд! Счёт: "
плюсы обычно не делают на отдельных строчках, так вывод занимает очень много места

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +        while (totalValue > 21 && aceCount > 0) {
магическая константа

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +    public static int playRound(int round) {
нужно декомпозировать этот метод, сейчас он делает слишком много

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +            return 1;
лучше заменить на Enum

2024-09-16 06:31 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/lebedev/MainTest.java
> +class MainTest {
лучше разбить на несколько классов, в каждом из которых будет тестироваться отдельный класс CardTest, DeckTest, ...

2024-09-16 06:35 UTC, Nikolay56615 commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +                System.out.println("Вы выиграли раунд! Счёт: "
Я не знаю почему, но этого от меня требовал checkstyle

2024-09-16 06:37 UTC, Nikolay56615 commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +        while (totalValue > 21 && aceCount > 0) {
? Я использовал ее для случаев, когда есть туз в руке и нужно уменьшить его значение с 11 до 1

2024-09-16 06:40 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +                System.out.println("Вы выиграли раунд! Счёт: "
а, ему надо, чтобы ты плюс переносил на следующую строчку, вот так
![image](https://github.com/user-attachments/assets/d72e2bf6-7737-4a4a-be91-1f695be2b19b)

2024-09-16 06:45 UTC, Nikolay56615 commented on Task_1_1_2/src/test/java/ru/nsu/lebedev/MainTest.java
> +class MainTest {
Хорошо, а вы можете подсказать, о чем в этих тестах идет речь?
![image](https://github.com/user-attachments/assets/f5a7a2eb-35dd-4adf-ab12-2f2797e3880c)

2024-09-16 06:48 UTC, Nikolay56615 commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +                System.out.println("Вы выиграли раунд! Счёт: "
Вообще, конкретно в чем проблема я не был уверен, вероятно плюс действительно должен был быть слева, а не справа, но, по крайней мере он больше не пишет это как ошибку)
![image](https://github.com/user-attachments/assets/278271d0-1d57-448a-89b8-87833aff6aca)

2024-09-16 06:49 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/lebedev/MainTest.java
> +class MainTest {
Ты используешь переменную сильно позже, чем объявляешь, ему это не нравится. В твоём случае её надо сделать final

2024-09-16 06:49 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/lebedev/MainTest.java
> +class MainTest {
так ты покажешь, что эта переменная сохраняет значение

2024-09-22 06:32 UTC, galinabykova requested changes

2024-09-22 06:32 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +    public static int winCount = 21;
final и именовать как надо именовать константы по стилю WIN_COUNT

2024-09-22 06:32 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/lebedev/Main.java
> +    public static int maximumDealerClearance = 17;
final MAXIMUM_DEALER_CLEARANCE

2024-09-22 06:32 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/lebedev/MainTest.java
> +    void testMain1() {
тестам лучше давать более осмысленные названия

2024-09-22 11:05 UTC, galinabykova approved these changes

2024-09-22 12:18 UTC, merged