Task_1_1_3
Nikolay56615/OOP pull request #8
Opened 2024-09-28 09:50 UTC by Nikolay56615

2024-09-29 16:30 UTC, galinabykova requested changes
хорошее первое решение, мягкий засчитан

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Add.java
> +package ru.nsu.lebedev;
в следующей лабе добавляй в название кусочек про лабу ru.nsu.lebedev.expression

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Add.java
> +package ru.nsu.lebedev;
(в этой не надо, пакет иногда запарно переименовывать)

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract void print();
перевод выражения в строчку не обязательно связан с выводом его на экран. Поэтому предлагаю переопределить метод toString в каждом наследнике, а print сделать не абстрактным, а с реализацией
`System.out.println(this)`
Так мы разделим вывод на экран и формирование строки - две разные функциональности (и ты сделаешь toString)

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    private Map<String, Integer> parseVariables(String input) {
что произойдёт в этом методе, если строка будет некорректной?

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    public void setUp() throws Exception {
а почему throws Exception?

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Variable.java
> +    public int eval(Map<String, Integer> var) {
если ты решил, что при отсутствии переменной нужно возвращать 0, нужно прописать это в документации. Почему ты выбрал этот способ, а не, например, исключение?

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    void derivativeAdd() throws Exception {
обрати внимание, что если бы у тебя был переопределён метод toString, не зависящий от System.out, тут бы не надо было переопределять вывод. Можно было просто протестировать toString (а print можно было не тестировать, потому что он простой)

2024-09-29 16:30 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/VariableTest.java
> +    void evalVariableAndDerivative() throws Exception {
лучше делать отдельные тесты для разных функциональностей, так проще локализовать ошибку. Обрати внимание, что невыполнение assertEquals завершает тест: это значит, что если в 54-й строчке тест упадёт, остальное просто не выполнится. Если ты тестируешь несколько независимых друг от друга штук, это, скорее  всего, не то поведение, которое ты ждёшь. Приятно сразу узнать обо всех косяках, это позволит быстрее найти ошибку

2024-09-29 16:43 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    public void setUp() throws Exception {
Когда я пишу в идеа, мне она предлагает, как можно доработать код, этот throws Exception она сама вставила, я подумал, что лишним не будет, тем более, что как ошибка он не высвечивается нигде

2024-09-29 16:46 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    void derivativeAdd() throws Exception {
![image](https://github.com/user-attachments/assets/fa00f893-3543-49bc-9cf3-50ffef0aa5d1)
Я просто не был уверен в том, как мне это воспринимать. Изначально, у меня как раз таки был toString, а потом я переделал под System.out

2024-09-29 16:47 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Add.java
> +package ru.nsu.lebedev;
Просто немного различные названия пакетов в каждой лабе? Не нужно писать тогда ru.nsu.lebedev.task_1_1_3?

2024-09-29 16:52 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Add.java
> +package ru.nsu.lebedev;
можно и так, да, главное, чтобы у тебя пакет состоял из твоего "уникального" идентификатора разработчика и названия, связанного с лабой

2024-09-29 16:54 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    void derivativeAdd() throws Exception {
Ага, тут сложно, на всякий случай уточню, я предлагаю тебе оставить твою сигнатуру, просто выделить создание строки в отдельный метод

2024-09-29 16:54 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    private Map<String, Integer> parseVariables(String input) {
Вообще, изначально я делал просто со словарем, потом подумал, что это не совсем то, что от меня просили по условию задачи
![image](https://github.com/user-attachments/assets/478bde2c-eb99-4a09-9692-b09acd1ddd84)
![image](https://github.com/user-attachments/assets/8a531ccb-2b6e-4774-baed-4656369427ba)
Он все верно посчитает, так как у меня в Variable указано, что стандартное значение переменной равно 0, если он не может его считать

2024-09-29 16:55 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    public void setUp() throws Exception {
хмм, интересно, я не увидела, где она нашла исключение в этом примере, но, хорошо)

2024-09-29 16:57 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    public void setUp() throws Exception {
![image](https://github.com/user-attachments/assets/55e2bc1d-37dc-48c9-8dbf-22758c56942e)
Она его и не видела, буквально сама предлагает вставить

2024-09-29 17:00 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    void derivativeAdd() throws Exception {
![image](https://github.com/user-attachments/assets/137b5013-140a-411d-bbf1-20962be8d906)
Вы имеете ввиду форматирование в таком виде сделать?

2024-09-29 17:01 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    public void setUp() throws Exception {
![image](https://github.com/user-attachments/assets/015b1fa5-5d7e-49a9-b158-9b6d85e7202a)
Она ее и не видела, буквально сама предлагает вставить

2024-09-29 17:10 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Variable.java
> +    public int eval(Map<String, Integer> var) {
![image](https://github.com/user-attachments/assets/bf656c0e-f3bb-4ee1-9bdc-2a1d30fff54b)
В примере задачи нам в eval вставляли еще и значение для переменной y, которую в уравнении не использовали, я подумал, что лучше добавить 0 для случаев, если происходит подсчет или дифференцирование по другой переменной, в том числе и несуществующей. С исключениями бы получилось больше кода, по ощущению.

2024-09-29 17:17 UTC, Nikolay56615 commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/VariableTest.java
> +    void evalVariableAndDerivative() throws Exception {
Вообще, я добавил Derivative в этот тест просто для того, чтобы подтвердить, что код возвращает рабочий Expression, который тоже можно подсчитать. Его по идее было достаточно один раз проверить, а не добавлять в каждый тестирующий класс. Я выделю его под отдельную функцию. В целом эту проверку создавал больше из собственного любопытства, чем из соображения тестирования)

2024-09-30 03:06 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Variable.java
> +    public int eval(Map<String, Integer> var) {
С исключениями получилось бы немного больше кода, это правда, но мне кажется, это не ключевое свойство для выбора поведения. Переделывать и дополнять ответ не надо, просто небольшой комментарий)

2024-09-30 03:07 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/AddTest.java
> +    void derivativeAdd() throws Exception {
ага

2024-09-30 03:09 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lebedev/VariableTest.java
> +    void evalVariableAndDerivative() throws Exception {
а, поняла)

2024-10-02 16:16 UTC, galinabykova requested changes

2024-10-02 16:16 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract String toString();
это переопределённый метод, надо добавить Override

2024-10-02 16:16 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract void print();
я предполагала, что ты сделаешь этот метод не абстрактным. По идее для всех классов подойдёт одна реализация: System.out.println(this)

2024-10-02 23:17 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract void print();
В целом, у меня и так в других классах именно так он и переопределен, но я могу убрать его из абстрактных

2024-10-02 23:18 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract String toString();
Везде вставил, кроме абстрактного)

2024-10-03 01:13 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract String toString();
Там же override, потому что toString из Object наследуется?

2024-10-03 01:32 UTC, Nikolay56615 commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract void print();
Я правильно понимаю, что нужно public void print();
 оставить только здесь, а из других классов удалить? Я просто думал, что в абстрактном классе желательно и все методы тоже абстрактными делать.

2024-10-03 08:08 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract String toString();
Ага)

2024-10-03 08:15 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lebedev/Expression.java
> +    public abstract void print();
Да, нет ничего плохого в том, чтобы делать реализации в абстрактном классе, это стандартное решение, убирающее дублирование кода. Если ты видишь конкретные минусы такого подхода, можем их обсудить)

2024-10-03 08:17 UTC, galinabykova approved these changes

2024-10-03 08:36 UTC, merged